"""Esquematico de ejemplo: driver de LED con transistor NPN."""

EXAMPLE = {
    "format": "circuitdraw",
    "version": 1,
    "components": [
        {"id": 0, "type": "source_dc", "x": -240, "y": 0, "rotation": 90, "mirrored": False,
         "reference": "V1", "value": "12V", "show_text": True},
        {"id": 1, "type": "ground", "x": -240, "y": 80, "rotation": 0, "mirrored": False,
         "reference": "", "value": "", "show_text": True},
        {"id": 2, "type": "resistor", "x": 60, "y": -80, "rotation": 90, "mirrored": False,
         "reference": "R1", "value": "470", "show_text": True},
        {"id": 3, "type": "led", "x": 60, "y": 0, "rotation": 90, "mirrored": False,
         "reference": "D1", "value": "rojo", "show_text": True},
        {"id": 4, "type": "npn", "x": 50, "y": 120, "rotation": 0, "mirrored": False,
         "reference": "Q1", "value": "BC547", "show_text": True},
        {"id": 5, "type": "ground", "x": 60, "y": 200, "rotation": 0, "mirrored": False,
         "reference": "", "value": "", "show_text": True},
        {"id": 6, "type": "resistor", "x": -60, "y": 120, "rotation": 0, "mirrored": False,
         "reference": "R2", "value": "10k", "show_text": True},
        {"id": 7, "type": "terminal", "x": -140, "y": 120, "rotation": 0, "mirrored": False,
         "reference": "", "value": "IN", "show_text": True},
    ],
    "wires": [
        {"points": [[-240, -30], [-240, -140], [60, -140], [60, -110]],
         "start": {"component": 0, "pin": 0}, "end": {"component": 2, "pin": 0}},
        {"points": [[-240, 30], [-240, 60]],
         "start": {"component": 0, "pin": 1}, "end": {"component": 1, "pin": 0}},
        {"points": [[60, -50], [60, -30]],
         "start": {"component": 2, "pin": 1}, "end": {"component": 3, "pin": 0}},
        {"points": [[60, 30], [60, 90]],
         "start": {"component": 3, "pin": 1}, "end": {"component": 4, "pin": 1}},
        {"points": [[60, 150], [60, 180]],
         "start": {"component": 4, "pin": 2}, "end": {"component": 5, "pin": 0}},
        {"points": [[20, 120], [-30, 120]],
         "start": {"component": 4, "pin": 0}, "end": {"component": 6, "pin": 1}},
        {"points": [[-90, 120], [-140, 120]],
         "start": {"component": 6, "pin": 0}, "end": {"component": 7, "pin": 0}},
    ],
    "texts": [
        {"x": -240, "y": -220, "size": 11,
         "text": "Driver de LED con transistor NPN\nR2 limita la corriente de base"},
    ],
}
